//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KAIE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nyheder
    {
        public int Id { get; set; }
        public string Titel { get; set; }
        public System.DateTime Dato { get; set; }
        public string Forfatter { get; set; }
        public byte[] Tekst { get; set; }
    }
}
