//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KAE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KAEDBContainer : DbContext
    {
        public KAEDBContainer()
            : base("name=KAEDBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdministratorSet> AdministratorSet1 { get; set; }
        public virtual DbSet<ForeningsTagSet> ForeningsTagSet1 { get; set; }
        public virtual DbSet<NyhedSet> NyhedSet1 { get; set; }
    }
}
