//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KAE
{
    using System;
    using System.Collections.Generic;
    
    public partial class NyhedSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NyhedSet()
        {
            this.ForeningsTagSet = new HashSet<ForeningsTagSet>();
        }
    
        public int Id { get; set; }
        public string Titel { get; set; }
        public System.DateTime Dato { get; set; }
        public string Tekst { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ForeningsTagSet> ForeningsTagSet { get; set; }
    }
}
